### PR TITLE
Feature/start page

### PR DESCRIPTION
**Pull request by bereba**
Added basic structure of landing page with all elements as suggested on the first overview as shown below.

Some links still need to be fixed.

[landing-page_idea.pdf](https://github.com/user-attachments/files/16727696/landing-page_idea.pdf)

### CODE REVIEW

**Comment by henhuy** [comment]
Fixed selection of results and model structure.
Combined collection and structure selection into one single selection, therefore.
Please have a look @bereba - thx

**Comment by henhuy** [comment]
Maybe you have to adjust 
https://github.com/sedos-project/sedos_dashboard/blob/4e0f5d50ecb4d0cd2bca3730055d852c1b4a9dba/sedos_dashboard/views.py#L10
in order to make it work, if you not have same collections/structures in your media folder...

**Comment by bereba** [comment]
Looks good to me. But if I understand it right I need a collection "steel_industry_test", right?
Which I do not have yet. Did you add it locally?

**Comment by bereba** [comment]
Therefore, "Look at Processes/Artifacts" is not working for me.

**Comment by henhuy** [comment]
> Looks good to me. But if I understand it right I need a collection "steel_industry_test", right? Which I do not have yet. Did you add it locally?

For testing purposes you could simply copy paste an existing collection and rename it to "steel_industry_test".

**Comment by bereba** [comment]
Ah okay, yes that works fine then.
We have to change the "Change Selection" url in the dashboard to the new start page then. Should I open a new branch for this?

**Pull request merged**
